[package]
name = "claude-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
seahash = "4.1"
dotenvy = "0.15"
serde_json = "1"
ureq = { version = "2", features = ["json"] }
regex = "1"
ollama-rs = "0.3.2"
tokio = { version = "1.0", features = ["full"] }
