name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-musl

    - name: Check compilation
      run: cargo check

    - name: Run tests
      run: cargo test

    - name: Build release
      run: cargo build --release

    - name: Upload release binary
      uses: actions/upload-artifact@v4
      with:
        name: claude-watch
        path: target/release/claude-watch