name: Build and Release Musl Version

on:
  push:
    tags:
      - 'v*'

# 添加必要的权限
permissions:
  contents: write
  packages: write
  workflow_dispatch:
    inputs:
      test_build:
        description: 'Test musl build without releasing'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-musl:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cross-rs/cross:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install musl tools and build dependencies
      run: |
        apt-get update && apt-get install -y musl musl-tools musl-dev make

    - name: Set up Rust toolchain
      run: |
        rustup default stable
        rustup target add x86_64-unknown-linux-musl

    - name: Show rustc version
      run: rustc --version && cargo --version

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-musl-${{ hashFiles('**/Cargo.lock') }}

    - name: Build musl version
      run: |
        export CC=musl-gcc
        export CXX=musl-gcc
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Test musl binary
      run: |
        ls -la target/x86_64-unknown-linux-musl/release/
        file target/x86_64-unknown-linux-musl/release/claude-watch
        ldd target/x86_64-unknown-linux-musl/release/claude-watch || echo "Static linking confirmed"
        ./target/x86_64-unknown-linux-musl/release/claude-watch --help

    - name: Create musl release directory
      run: |
        mkdir -p target/musl-release
        cp target/x86_64-unknown-linux-musl/release/claude-watch target/musl-release/
        strip target/musl-release/claude-watch
        ls -lh target/musl-release/claude-watch

    - name: Upload build artifacts
      if: inputs.test_build == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: claude-watch-musl
        path: target/musl-release/
        retention-days: 7

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') && inputs.test_build != 'true'
      uses: softprops/action-gh-release@v2
      with:
        files: target/musl-release/claude-watch
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Musl 版本发布

          这是一个静态链接的 musl 版本，可以在任何 Linux 系统上运行，无需依赖系统库。

          ### 特性
          - ✅ 完全静态链接，无外部依赖
          - ✅ 支持所有 Linux 发行版
          - ✅ 文件大小优化（stripped）
          - ✅ 包含完整功能

          ### 使用方法
          \`\`\`bash
          # 下载二进制文件
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/claude-watch

          # 赋予执行权限
          chmod +x claude-watch

          # 运行
          ./claude-watch --help
          \`\`\`

          ### 系统兼容性
          - Ubuntu 16.04+
          - Debian 8+
          - CentOS 7+
          - RHEL 7+
          - Fedora 25+
          - Arch Linux
          - Alpine Linux
          - 以及其他所有支持 glibc 的 Linux 发行版

          ### 版本信息
          - 构建环境: Ubuntu + Musl + Cross-rs

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}