name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build release
      run: cargo build --release

    - name: Check if binary exists
      run: |
        ls -la target/release/
        if [ -f "target/release/claude-watch" ]; then
          file target/release/claude-watch
          echo "Binary size: $(du -h target/release/claude-watch)"
        else
          echo "Error: Binary not found!"
          exit 1
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/claude-watch
        draft: false
        prerelease: false
        body: |
          Automated release created by GitHub Actions
          
          ## What's Changed
          * Updated Claude Code activity detection
          * Improved CI/CD workflows
          
          ## Assets
          * `claude-watch` - Precompiled binary for Linux (x86_64)
          
          ## Installation
          ```bash
          # Download the binary
          wget https://github.com/ModerRAS/claude-watch/releases/download/${{ github.ref_name }}/claude-watch
          chmod +x claude-watch
          ./claude-watch
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}